export const letterTips: Record<string, string> = {
  A: "Make a fist with a thumb on the side",
  B: "Curl all fingers down, thumb on top",
  C: "Curve your hand like the letter C",
  D: "Point index finger up, other fingers touch thumb",
  E: "Curl all fingers down to touch thumb",
  F: "Touch index finger to thumb, other fingers up",
  G: "Point index finger and thumb sideways",
  H: "Point index and middle fingers sideways",
  I: "Make a fist with pinky finger up",
  J: "Draw a J shape with your pinky",
  K: "Point index and middle fingers up, thumb between",
  L: "Make an L shape with thumb and index finger",
  M: "Tuck thumb under three fingers",
  N: "Tuck thumb under two fingers",
  O: "Make an O shape with all fingers",
  P: "Point index and middle fingers down, thumb between",
  Q: "Point index finger and thumb down",
  R: "Cross index and middle fingers",
  S: "Make a fist with thumb across fingers",
  T: "Tuck thumb between index and middle fingers",
  U: "Point index and middle fingers up together",
  V: "Make a V with index and middle fingers",
  W: "Point index, middle, and ring fingers up",
  X: "Hook index finger",
  Y: "Extend thumb and pinky, fold other fingers",
  Z: "Draw a Z shape with index finger",
};
